name: Release Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install setuptools wheel
          pip install -e '.[docs]'
      - name: Building Docs
        run: |
          sphinx-build docs public -b dirhtml
      - name: Github Pages Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          publish_branch: gh-pages
          publish_dir: public
